config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  get '/register' => 'users#new'
  get '/login' => 'sessions#new', as: "login"
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/profile' => 'users#profile', as: "profile"
  get 'availabilities/other' => 'availabilities#get_other'
  post 'availabilities/move' => 'availabilities#move'
  post 'availabilities/resize' => 'availabilities#resize'

  resources :bookings
  resources :events
  resources :challenges
  resources :availabilities
  resources :user_details
  resources :users, except: [:index, :edit, :update]

end

app/models/user.rb
class User < ActiveRecord::Base

  has_one :user_detail
  has_many :bookings
  has_many :events, through: :bookings
  has_many :availabilities


  has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :destroy]

  # GET /users/1
  # GET /users/1.json
  def profile
    @user = User.find_by(id: session[:user_id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to :profile, notice: 'User was successfully created.' }
        format.json { render :profile, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :avatar, :role)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, autocomplete: :off %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name, autocomplete: :off %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email, autocomplete: :off %>
  </div>
  <div class="field">
    <%= f.label "Password" %><br>
    <%= f.text_field :password, type: :password %>
  </div>
  <div class="field">
    <%= f.label "Role" %><br>
    <%= f.select :role, ["Student","Guide","Admin"], {prompt: 'Select Role'} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th>Avatar</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= user.avatar %></td>
        <td><%= user.role %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Login', login_path %>

app/views/users/profile.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @user.avatar %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<h1>Availabilities</h1>
<%= link_to("Make new availability", new_availability_path) %>

<% current_user.availabilities.each do |availability| %>
  <ul>
    <li>Time: from <%= availability.start %> to <%= availability.end %></li>
  </ul>
<% end %>


<h1>Group Availabilities</h1>

<% Availability.other_availabilities(current_user.id).each do |availability| %>
  <ul>
    <li>Time: from <%= availability.start %> to <%= availability.end %></li>
  </ul>
<% end %>

<div id='calendar'></div>
<div id = "desc_dialog" class="dialog" style ="display:none;">
  <div id = "event_desc">
  </div>
  <br/>
  <br/>
  <div id = "event_actions">
    <span id = "delete_event"></span>
  </div>
</div>
<div id = "create_event_dialog" class="dialog" style ="display:none;">
  <div id = "create_event">
  </div>

</div>