config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  get '/register' => 'users#new'
  get '/login' => 'sessions#new', as: "login"
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/profile' => 'users#profile', as: "profile"
  get 'availabilities/other' => 'availabilities#get_other'
  post 'availabilities/move' => 'availabilities#move'
  post 'availabilities/resize' => 'availabilities#resize'

  resources :bookings
  resources :events
  resources :challenges
  resources :availabilities
  resources :user_details
  resources :users, except: [:index, :edit, :update]

end

app/models/user_detail.rb
class UserDetail < ActiveRecord::Base
  belongs_to :user
end

app/controllers/user_details_controller.rb
class UserDetailsController < ApplicationController
  before_action :set_user_detail, only: [:show, :edit, :update, :destroy]

  # GET /user_details
  # GET /user_details.json
  def index
    @user_details = UserDetail.all
  end

  # GET /user_details/1
  # GET /user_details/1.json
  def show
  end

  # GET /user_details/new
  def new
    @user_detail = UserDetail.new
  end

  # GET /user_details/1/edit
  def edit
  end

  # POST /user_details
  # POST /user_details.json
  def create
    @user_detail = UserDetail.new(user_detail_params)

    respond_to do |format|
      if @user_detail.save
        format.html { redirect_to @user_detail, notice: 'User detail was successfully created.' }
        format.json { render :show, status: :created, location: @user_detail }
      else
        format.html { render :new }
        format.json { render json: @user_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_details/1
  # PATCH/PUT /user_details/1.json
  def update
    respond_to do |format|
      if @user_detail.update(user_detail_params)
        format.html { redirect_to @user_detail, notice: 'User detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_detail }
      else
        format.html { render :edit }
        format.json { render json: @user_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_details/1
  # DELETE /user_details/1.json
  def destroy
    @user_detail.destroy
    respond_to do |format|
      format.html { redirect_to user_details_url, notice: 'User detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_detail
      @user_detail = UserDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_detail_params
      params.require(:user_detail).permit(:prefer_in_person, :time_zone, :prefer_location_cohort, :slack_handle, :phone, :cohort, :year, :location)
    end
end

app/helpers/user_details_helper.rb
module UserDetailsHelper
end

app/views/user_details/_form.html.erb
<%= form_for(@user_detail) do |f| %>
  <% if @user_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_detail.errors.count, "error") %> prohibited this user_detail from being saved:</h2>

      <ul>
      <% @user_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :prefer_in_person %><br>
    <%= f.check_box :prefer_in_person %>
  </div>
  <div class="field">
    <%= f.label :time_zone %><br>
    <%= f.text_field :time_zone %>
  </div>
  <div class="field">
    <%= f.label :prefer_location_cohort %><br>
    <%= f.check_box :prefer_location_cohort %>
  </div>
  <div class="field">
    <%= f.label :slack_handle %><br>
    <%= f.text_field :slack_handle %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :cohort %><br>
    <%= f.text_field :cohort %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_details/edit.html.erb
<h1>Editing User Detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_detail %> |
<%= link_to 'Back', user_details_path %>

app/views/user_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Details</h1>

<table>
  <thead>
    <tr>
      <th>Prefer in person</th>
      <th>Time zone</th>
      <th>Prefer location cohort</th>
      <th>Slack handle</th>
      <th>Phone</th>
      <th>Cohort</th>
      <th>Year</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_details.each do |user_detail| %>
      <tr>
        <td><%= user_detail.prefer_in_person %></td>
        <td><%= user_detail.time_zone %></td>
        <td><%= user_detail.prefer_location_cohort %></td>
        <td><%= user_detail.slack_handle %></td>
        <td><%= user_detail.phone %></td>
        <td><%= user_detail.cohort %></td>
        <td><%= user_detail.year %></td>
        <td><%= user_detail.location %></td>
        <td><%= link_to 'Show', user_detail %></td>
        <td><%= link_to 'Edit', edit_user_detail_path(user_detail) %></td>
        <td><%= link_to 'Destroy', user_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User detail', new_user_detail_path %>

app/views/user_details/new.html.erb
<h1>New User Detail</h1>

<%= render 'form' %>

<%= link_to 'Back', user_details_path %>

app/views/user_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Prefer in person:</strong>
  <%= @user_detail.prefer_in_person %>
</p>

<p>
  <strong>Time zone:</strong>
  <%= @user_detail.time_zone %>
</p>

<p>
  <strong>Prefer location cohort:</strong>
  <%= @user_detail.prefer_location_cohort %>
</p>

<p>
  <strong>Slack handle:</strong>
  <%= @user_detail.slack_handle %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user_detail.phone %>
</p>

<p>
  <strong>Cohort:</strong>
  <%= @user_detail.cohort %>
</p>

<p>
  <strong>Year:</strong>
  <%= @user_detail.year %>
</p>

<p>
  <strong>Location:</strong>
  <%= @user_detail.location %>
</p>

<%= link_to 'Edit', edit_user_detail_path(@user_detail) %> |
<%= link_to 'Back', user_details_path %>