config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  get '/register' => 'users#new'
  get '/login' => 'sessions#new', as: "login"
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/profile' => 'users#profile', as: "profile"
  get 'availabilities/other' => 'availabilities#get_other'
  post 'availabilities/move' => 'availabilities#move'
  post 'availabilities/resize' => 'availabilities#resize'

  resources :bookings
  resources :events
  resources :challenges
  resources :availabilities
  resources :user_details
  resources :users, except: [:index, :edit, :update]

end

app/models/availability.rb
class Availability < ActiveRecord::Base
  belongs_to :user
  belongs_to :challenge, foreign_key: "desired_challenge_id"

  def self.other_availabilities(user_id)
    where.not(user_id: user_id)
  end
end

app/controllers/availabilities_controller.rb
class AvailabilitiesController < ApplicationController
  before_action :set_availability, only: [:show, :edit, :update, :destroy]

  # GET /availabilities
  # GET /availabilities.json
  def index
    @availabilities = Availability.where(user: current_user)
  end

  # GET /availabilities/1
  # GET /availabilities/1.json
  def show
  end

  # GET /availabilities/new
  def new
    @availability = Availability.new
  end

  # GET /availabilities/1/edit
  def edit
  end

  # POST /availabilities
  # POST /availabilities.json
  def create
    @availability = Availability.new(availability_params)
    @availability.user_id = session[:user_id]

    respond_to do |format|
      if @availability.save
        format.html { redirect_to @availability, notice: 'Availability was successfully created.' }
        format.json { render :show, status: :created, location: @availability }
      else
        format.html { render :new }
        format.json { render json: @availability.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /availabilities/1
  # PATCH/PUT /availabilities/1.json
  def update
    respond_to do |format|
      if @availability.update(availability_params)
        format.html { redirect_to @availability, notice: 'Availability was successfully updated.' }
        format.json { render :show, status: :ok, location: @availability }
      else
        format.html { render :edit }
        format.json { render json: @availability.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /availabilities/1
  # DELETE /availabilities/1.json
  def destroy
    @availability.destroy
    respond_to do |format|
      format.html { redirect_to availabilities_url, notice: 'Availability was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get_other
    user = User.find_by(id: session[:user_id])
    other_availabilities = Availability.other_availabilities(user.id)
    event_objects = other_availabilities.map do |availability|
      { :color => '#34AADC', :title => 'Group', :start => "#{availability.start.iso8601}", :end => "#{availability.end.iso8601}", :allDay => false, :overlap => false, id: availability.id, type: "group"}
    end
    user.availabilities.each do |availability|
      event_objects << { :color => '#C2110D', :title => 'Individual', :start => "#{availability.start.iso8601}", :end => "#{availability.end.iso8601}", :allDay => false, :overlap => false, id: availability.id, type: "user"}
    end
    render json: event_objects
  end



  def move
    @availability = Availability.find_by_id(params[:id])
    if @availability
      @availability.start = (params[:minute_delta].to_i).minutes.from_now((params[:day_delta].to_i).days.from_now(@availability.start))
      @availability.end = (params[:minute_delta].to_i).minutes.from_now((params[:day_delta].to_i).days.from_now(@availability.end))
      @availability.save
    end
    render :nothing => true
  end

  def resize
    @availability = Availability.find_by_id(params[:id])
    if @availability
      @availability.end = (params[:minute_delta].to_i).minutes.from_now((params[:day_delta].to_i).days.from_now(@availability.end))
      @availability.save
    end
    render :nothing => true
  end

  def destroy
    @availability = Availability.find_by(id: params[:id])
    @availability.destroy
    render :nothing => true
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_availability
      @availability = Availability.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def availability_params
      params.require(:availability).permit(:start, :end, :status, :user_id, :desired_challenge_id, :enforce_boundaries)
    end
end

app/helpers/availabilities_helper.rb
module AvailabilitiesHelper
end

app/views/availabilities/_form.html.erb
<%= form_for(@availability) do |f| %>
  <% if @availability.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@availability.errors.count, "error") %> prohibited this availability from being saved:</h2>

      <ul>
      <% @availability.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start %><br>
    <%= f.datetime_select :start, ampm: true, default: 1.day.from_now %>
  </div>
  <div class="field">
    <%= f.label :end %><br>
    <%= f.datetime_select :end, ampm: true, default: 1.day.from_now %>
  </div>
  <div class="field">
    <%= f.label "Desired challenge (optional)" %><br>
    <%= f.text_field :desired_challenge_id %>
  </div>
  <div class="field">
    <%= f.label "Enforce boundaries?" %><br>
    <%= f.check_box :enforce_boundaries %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/availabilities/edit.html.erb
<h1>Editing Availability</h1>

<%= render 'form' %>

<%= link_to 'Show', @availability %> |
<%= link_to 'Back', availabilities_path %>

app/views/availabilities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Availabilities</h1>

<table>
  <thead>
    <tr>
      <th>Start</th>
      <th>End</th>
      <th>Status</th>
      <th>User</th>
      <th>Desired challenge</th>
      <th>Enforce boundaries</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @availabilities.each do |availability| %>
      <tr>
        <td><%= availability.start %></td>
        <td><%= availability.end %></td>
        <td><%= availability.status %></td>
        <td><%= availability.user_id %></td>
        <td><%= availability.desired_challenge_id %></td>
        <td><%= availability.enforce_boundaries %></td>
        <td><%= link_to 'Show', availability %></td>
        <td><%= link_to 'Edit', edit_availability_path(availability) %></td>
        <td><%= link_to 'Destroy', availability, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Availability', new_availability_path %>

app/views/availabilities/new.html.erb
<h1>New Availability</h1>

<%= render 'form' %>

<%= link_to 'Back', availabilities_path %>

app/views/availabilities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start:</strong>
  <%= @availability.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @availability.end %>
</p>

<p>
  <strong>Status:</strong>
  <%= @availability.status %>
</p>

<p>
  <strong>User:</strong>
  <%= @availability.user_id %>
</p>

<p>
  <strong>Desired challenge:</strong>
  <%= @availability.desired_challenge_id %>
</p>

<p>
  <strong>Enforce boundaries:</strong>
  <%= @availability.enforce_boundaries %>
</p>

<%= link_to 'Edit', edit_availability_path(@availability) %> |
<%= link_to 'Back', profile_path %>